# Generated by Django 2.1.7 on 2019-02-18 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinner',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
