# Generated by Django 2.1.7 on 2019-02-18 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middager', '0002_dinner_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinner',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
